server:
        port: 8090


spring:
        thymeleaf:
                prefix: classpath:/templates/
                suffix: .html
                mode: HTML
                encoding: UTF-8
                cache: false
        freemarker:
                check-template-location: false
        redis:
                database: 0
                host: 127.0.0.1
                port: 6379
                password: lgyTT
                jedis:
                        pool:
                                min-idle: 0
                                max-idle: 8
                                max-wait: -1
                                max-active: 8
                timeout: 0
        datasource:
                url: jdbc:mysql://127.0.0.1:3306/mytest?serverTimezone=UTC&useSSL=false
                username: root
                password: 1234xy
                # 使用druid数据源
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                filters: stat
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
        #mongo配置
        data:
                mongodb:
                        database: me
                        uri: mongodb://127.0.0.1:27017
                        username: lgyTT
                        password: 1234xy

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
        mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
        type-aliases-package: com.lgy.demo.entity  # 注意：对应实体类的路径


